name: Publish to NPM

on:
  push:
    paths:
      - '.changeset/**'
      - 'packages/**'
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js 12.x
        uses: actions/setup-node@master
        with:
          node-version: 12.x

      - name: Removes cache
        run: npm cache clean -f

      - name: NPM Version
        run: npm --version

      - name: NPM Version
        run: node --version

      - name: Install Dependencies
        run: npm run install:all

      - name: Setup CI Git User
        run: |
          git config --global user.email "nsk9195@gmail.com"
          git config --global user.name "shubhamkaushal"

      - name: Build packages
        run: npm run build
      
      - name: Run tests
        run: npm test

      - name: Publish packages
        uses: changesets/action@master
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: npm run release
          commit: "chore(release): version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
